### ISSUE TITLE
Fresh server won't gather instructions and locks at Getting roles.

### ISSUE THREAD

**Issue by joshhamon** [J053Fabi0/Duplicated-files-cleaner-Incognito#3]
Two new servers, neither are able to run the script, here's the output:

```
Database loaded.
Getting instructions.
Instructions:
[]

Getting roles.
  TypeError: Promise.allSettled is not a function
      at getNodesInfo (/root/Duplicated-files-cleaner-Incognito/getNodesInfo.js:14:17)
      at /root/Duplicated-files-cleaner-Incognito/index.js:17:25
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by J053Fabi0** [comment]
Hello, Josh. This is most likely because you don't meet the minimum requirement for the node version. Could you check that out?

**Comment by J053Fabi0** [comment]
Was that the problem? Can I close this issue?
